# Generated by Django 4.1.7 on 2023-03-22 20:53

from django.db import migrations, models
import embed_video.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='References',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('video', embed_video.fields.EmbedVideoField(blank=True, null=True, verbose_name='видео')),
                ('title', models.CharField(max_length=50, verbose_name='название')),
                ('description', models.CharField(max_length=250, verbose_name='описание')),
            ],
        ),
        migrations.CreateModel(
            name='Work',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, upload_to='images/', verbose_name='изображение')),
                ('name', models.CharField(max_length=50, verbose_name='имя')),
                ('sub_title', models.CharField(max_length=100, verbose_name='название')),
                ('description', models.CharField(max_length=150, verbose_name='описание')),
                ('text', models.TextField(max_length=2500, verbose_name='текст')),
                ('created_up', models.DateTimeField(auto_now_add=True, verbose_name='дата создание')),
            ],
        ),
    ]
